### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by M3tt3k** [CptSnuffy/lost-ark-farming-tool#1]

**Comment by CptSnuffy** [comment]
Hi, this project still isn't quite done (It almost is! A working version should come out sometime today) The way it will work though is that it will press a key that you selected(using pynput) for it every x amount of seconds (you also pick the amount of time in between these presses) it's not a very complicated program and I don't intend on any updates for it once it is completely functional as it really is just a project for my friends to use.
